<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { listen, type UnlistenFn } from '@tauri-apps/api/event'
import { open } from '@tauri-apps/plugin-dialog'
import { Home, Search, Heart, History, Download, Library, Settings as SettingsIcon, Play, Pause, SkipBack, SkipForward, Volume2, ListMusic, MoreHorizontal, ArrowDownToLine, RefreshCw, FolderSearch, Trash2, X, GripVertical, Radio, Wifi, WifiOff, Music2, ChevronRight, Check, Shuffle, Repeat2 } from 'lucide-vue-next'
import { api } from './api'
import type { Download as Dl, Settings, Source, Track } from './types'

type Page='home'|'search'|'favorites'|'history'|'downloads'|'library'|'settings'
const page=ref<Page>('home'), ready=ref(false), onboarding=ref(false), onboardingStep=ref(0), query=ref(''), searching=ref(false), connection=ref('offline')
const results=ref<Track[]>([]), favorites=ref<Track[]>([]), history=ref<Track[]>([]), library=ref<Track[]>([]), downloads=ref<Dl[]>([]), queue=ref<Track[]>([])
const current=ref<Track|null>(null), playerState=ref('idle'), position=ref(0), duration=ref(0), buffered=ref(0), volume=ref(80), muted=ref(false), cacheUsed=ref(0)
const showQueue=ref(false), sourceTrack=ref<Track|null>(null), toast=ref(''), unlisteners:UnlistenFn[]=[]
const settings=ref<Settings>({username:'',password:'',autoAccount:true,selectorMode:'balanced',preferLossless:true,preferFlac:true,minimumBitrate:192,bufferSeconds:0,prefetchCount:2,cacheLimitGb:10,downloadDirectory:'',organizeDownloads:true,bandwidthLimit:0,slskdUrl:'http://127.0.0.1:5030',apiKey:'',closeToTray:true})
const nav=[['home','首页',Home],['search','搜索',Search],['favorites','收藏',Heart],['history','最近播放',History],['downloads','下载',Download],['library','本地音乐',Library]] as const
const fmt=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`
const bytes=(n:number)=>n?`${(n/1024/1024).toFixed(n>1024**3?1:0)} MB`:'0 MB'
const pageTitle=computed(()=>nav.find(n=>n[0]===page.value)?.[1]||'设置')
function say(s:string){toast.value=s;setTimeout(()=>{if(toast.value===s)toast.value=''},2600)}
async function boot(){try{const b=await api.bootstrap();settings.value={...settings.value,...b.settings};favorites.value=b.favorites||[];history.value=b.history||[];downloads.value=b.downloads||[];queue.value=b.queue||[];results.value=b.tracks||[];connection.value=b.connection;cacheUsed.value=b.cacheUsed||0;onboarding.value=!b.onboarded}catch(e){say(String(e))}finally{ready.value=true}}
async function doSearch(refresh=false){if(!query.value.trim())return;page.value='search';searching.value=true;try{results.value=await api.search(query.value.trim(),refresh)}catch(e){say(String(e))}finally{searching.value=false}}
async function play(t:Track){current.value=t;duration.value=t.duration||0;playerState.value='searching_source';try{await api.command('play_track',{trackId:t.id});if(!queue.value.some(x=>x.id===t.id))queue.value.push(t)}catch(e){playerState.value='error';say(String(e))}}
async function toggle(){const name=playerState.value==='playing'?'pause':'resume';await api.command(name);playerState.value=name==='pause'?'paused':'playing'}
async function seek(e:Event){const v=Number((e.target as HTMLInputElement).value);if(v>buffered.value&&buffered.value<duration.value){position.value=buffered.value;say('目标位置尚未缓存')}else{position.value=v;await api.command('seek',{position:v})}}
async function next(){await api.command('next');const i=queue.value.findIndex(x=>x.id===current.value?.id);if(queue.value[i+1])current.value=queue.value[i+1]}
async function previous(){await api.command('previous')}
async function favorite(t:Track){t.favorite=!t.favorite;await api.command('favorite_track',{trackId:t.id,favorite:t.favorite});favorites.value=t.favorite?[t,...favorites.value.filter(x=>x.id!==t.id)]:favorites.value.filter(x=>x.id!==t.id)}
async function addQueue(t:Track){await api.command('add_to_queue',{trackId:t.id});if(!queue.value.some(x=>x.id===t.id))queue.value.push(t);say('已加入播放队列')}
async function removeQueue(i:number){await api.command('remove_from_queue',{index:i});queue.value.splice(i,1)}
async function downloadTrack(t:Track){await api.command('download_track',{trackId:t.id,preference:'auto'});downloads.value=await api.downloads();say('已加入下载')}
async function pickFolder(){const p=await open({directory:true,multiple:false});if(typeof p==='string')settings.value.downloadDirectory=p}
async function scan(){const p=await open({directory:true,multiple:false});if(typeof p==='string'){library.value=await api.scanLibrary(p);page.value='library'}}
async function save(){await api.saveSettings(settings.value);say('设置已保存')}
async function finishOnboarding(){if(settings.value.autoAccount){if(!settings.value.username)settings.value.username='SoulMusic_'+Math.random().toString(36).slice(2,8).toUpperCase();if(!settings.value.password)settings.value.password=crypto.randomUUID().replaceAll('-','').slice(0,20)}await api.saveSettings(settings.value);await api.command('complete_onboarding',{acceptedCopyright:true});onboarding.value=false;connection.value='connecting';connection.value=await api.command<string>('reconnect');say(connection.value==='connected'?'Soulseek 已连接':'账号已保存，Soulseek 正在连接')}
async function reconnect(){connection.value='connecting';try{connection.value=await api.command<string>('reconnect');say(connection.value==='connected'?'已连接 Soulseek':'连接失败，请检查 slskd 设置')}catch(e){connection.value='offline';say(String(e))}}
async function clearCache(){const freed=await api.command<number>('clear_cache');cacheUsed.value=Math.max(0,cacheUsed.value-(freed||cacheUsed.value));say('缓存已清理')}
function rows():Track[]{return page.value==='favorites'?favorites.value:page.value==='history'?history.value:page.value==='library'?library.value:results.value}
onMounted(async()=>{if('__TAURI_INTERNALS__' in window){for(const [event,fn] of [['connection://state',(e:any)=>connection.value=e.payload],['player://state',(e:any)=>playerState.value=e.payload],['player://position',(e:any)=>{position.value=e.payload.position;duration.value=e.payload.duration;buffered.value=e.payload.buffered}],['player://track',(e:any)=>current.value=e.payload],['transfer://progress',async()=>downloads.value=await api.downloads()],['queue://updated',(e:any)=>queue.value=e.payload]] as const)unlisteners.push(await listen(event,fn))}await boot()})
onUnmounted(()=>unlisteners.forEach(x=>x()))
</script>

<template>
 <div v-if="!ready" class="splash"><div class="logo"><Music2/></div><h1>SoulMusic</h1><p>正在准备你的音乐空间…</p></div>
 <div v-else class="app">
  <aside class="sidebar">
   <div class="brand"><div class="brand-icon"><Music2 :size="22"/></div><b>SoulMusic</b></div>
   <nav><button v-for="[id,label,Icon] in nav" :key="id" :class="{active:page===id}" @click="page=id"><component :is="Icon" :size="19"/><span>{{label}}</span></button></nav>
   <div class="sidebar-status"><span :class="['dot',connection]"></span><span>{{connection==='connected'?'Soulseek 已连接':connection==='connecting'?'正在连接':'Soulseek 未连接'}}</span></div>
   <button class="settings-link" :class="{active:page==='settings'}" @click="page='settings'"><SettingsIcon :size="19"/>设置</button>
  </aside>
  <main>
   <header><div><small>MY MUSIC</small><h1>{{pageTitle}}</h1></div><form class="top-search" @submit.prevent="doSearch()"><Search :size="19"/><input v-model="query" placeholder="搜索歌曲、歌手或专辑"/><button>搜索</button></form><div class="avatar">{{(settings.username||'S').slice(0,1).toUpperCase()}}</div></header>
   <section class="content">
    <template v-if="page==='home'">
     <div class="hero"><div><span class="eyebrow">YOUR SOUND, YOUR SOUL</span><h2>每一首想听的歌，<br/><i>都离你很近。</i></h2><p>搜索、自动选源、缓冲播放。复杂的网络，简单的音乐。</p><button class="primary" @click="page='search'"><Search :size="17"/>开始搜索</button></div><div class="hero-art"><div class="disc"><div></div></div><span class="note n1">♪</span><span class="note n2">♫</span></div></div>
     <div class="section-head"><h2>最近播放</h2><button @click="page='history'">查看全部 <ChevronRight :size="16"/></button></div>
     <div v-if="history.length" class="track-grid"><article v-for="t in history.slice(0,6)" :key="t.id" class="track-card" @dblclick="play(t)"><div class="cover" :style="{'--seed':t.id.length*23}"><Music2/><button @click="play(t)"><Play fill="currentColor"/></button></div><b>{{t.title}}</b><span>{{t.artist}}</span></article></div>
     <div v-else class="empty-inline"><History/><span>播放过的歌曲会出现在这里</span></div>
     <div class="two-columns"><div><div class="section-head"><h2>最近搜索</h2></div><div class="chips"><button v-for="q in ['周杰伦','Taylor Swift','陈奕迅','Linkin Park']" @click="query=q;doSearch()">{{q}}</button></div></div><div class="discover"><Radio/><div><b>随机发现</b><p>从你的音乐口味中发现新声音</p></div><button @click="query=settings.username?'猜你喜欢':'周杰伦';doSearch()"><Shuffle/></button></div></div>
    </template>
    <template v-else-if="page==='search'||page==='favorites'||page==='history'||page==='library'">
     <div v-if="page==='search'" class="search-banner"><div><h2>{{query?'“'+query+'”':'搜索整个 Soulseek 网络'}}</h2><p>{{searching?'正在从多个来源收集结果…':results.length?`聚合为 ${results.length} 首歌曲`:'输入歌曲、歌手或专辑开始探索'}}</p></div><button v-if="query" class="icon-btn" :class="{spin:searching}" @click="doSearch(true)"><RefreshCw/></button></div>
     <div v-if="page==='library'" class="toolbar"><p>扫描本地音频并读取标签、封面和音质信息</p><button class="primary" @click="scan"><FolderSearch/>扫描文件夹</button></div>
     <div v-if="rows().length" class="track-list"><div class="list-head"><span>#</span><span>歌曲</span><span>音质</span><span>来源</span><span>时长</span><span></span></div><div v-for="(t,i) in rows()" :key="t.id" class="track-row" :class="{current:current?.id===t.id}"><span class="index">{{i+1}}</span><button class="mini-cover" @click="play(t)"><Music2/><Play class="play-overlay" fill="currentColor"/></button><div class="meta"><b>{{t.title}}</b><span>{{t.artist}}<template v-if="t.album"> · {{t.album}}</template></span></div><span class="quality">{{t.formats?.join(' · ')||'LOCAL'}}</span><button class="sources" @click="sourceTrack=t">{{t.sourceCount||1}} 个来源</button><span>{{fmt(t.duration)}}</span><div class="actions"><button @click="favorite(t)"><Heart :fill="t.favorite?'currentColor':'none'" :class="{loved:t.favorite}"/></button><button @click="downloadTrack(t)"><ArrowDownToLine/></button><button @click="addQueue(t)"><ListMusic/></button><button @click="sourceTrack=t"><MoreHorizontal/></button></div></div></div>
     <div v-else class="empty"><component :is="page==='favorites'?Heart:page==='history'?History:page==='library'?Library:Search"/><h2>{{page==='favorites'?'还没有收藏':page==='history'?'还没有播放记录':page==='library'?'本地音乐库为空':'没有找到音乐'}}</h2><p>{{page==='search'?'试试简化关键词，或只搜索歌手和歌名':'你的内容会在这里整齐出现'}}</p></div>
    </template>
    <template v-else-if="page==='downloads'">
     <div class="tabs"><button class="active">全部</button><button>正在下载</button><button>已完成</button><button>失败</button></div>
     <div v-if="downloads.length" class="download-list"><article v-for="d in downloads" :key="d.id"><div class="mini-cover"><Music2/></div><div class="download-main"><div><b>{{d.track.title}}</b><span>{{d.track.artist}}</span></div><div class="progress"><i :style="{width:(d.downloadedBytes/Math.max(1,d.totalBytes)*100)+'%'}"></i></div><small>{{bytes(d.downloadedBytes)}} / {{bytes(d.totalBytes)}} · {{bytes(d.speed)}}/s · {{d.status}}</small></div><button class="icon-btn" @click="api.command('cancel_download',{id:d.id})"><X/></button></article></div>
     <div v-else class="empty"><Download/><h2>下载列表空空的</h2><p>永久保存的歌曲会显示在这里，缓存不会混入其中</p></div>
    </template>
    <template v-else-if="page==='settings'">
     <div class="settings-page">
      <section><div class="setting-title"><div class="setting-icon coral"><Wifi/></div><div><h2>Soulseek</h2><p>网络账户与本地服务</p></div><span :class="['status-pill',connection]">{{connection==='connected'?'已连接':'未连接'}}</span></div><div class="form-grid"><label>用户名<input v-model="settings.username"/></label><label>密码<input v-model="settings.password" type="password" placeholder="由 Windows 安全存储"/></label><label class="wide">slskd 地址<input v-model="settings.slskdUrl"/></label><label class="wide">API Key<input v-model="settings.apiKey" type="password"/></label></div><button class="secondary" @click="reconnect"><RefreshCw/>重新连接</button></section>
      <section><div class="setting-title"><div class="setting-icon purple"><Music2/></div><div><h2>音质与播放</h2><p>自动选择最合适的音乐来源</p></div></div><div class="segmented"><button v-for="m in [['speed','速度优先'],['balanced','平衡'],['quality','音质优先']]" :class="{active:settings.selectorMode===m[0]}" @click="settings.selectorMode=m[0]">{{m[1]}}</button></div><div class="toggles"><label><span><b>优先无损</b><small>有可用且速度合适的无损来源时优先</small></span><input type="checkbox" v-model="settings.preferLossless"/></label><label><span><b>优先 FLAC</b><small>无损格式中优先选择兼容性更好的 FLAC</small></span><input type="checkbox" v-model="settings.preferFlac"/></label></div><div class="form-grid"><label>最低 MP3 码率<select v-model="settings.minimumBitrate"><option :value="128">128K</option><option :value="192">192K</option><option :value="256">256K</option><option :value="320">320K</option></select></label><label>预缓冲<select v-model="settings.bufferSeconds"><option :value="0">自动</option><option v-for="n in [5,10,15,30]" :value="n">{{n}} 秒</option></select></label><label>预加载下一首<select v-model="settings.prefetchCount"><option v-for="n in [0,1,2,3]" :value="n">{{n}} 首</option></select></label><label>速度限制<select v-model="settings.bandwidthLimit"><option :value="0">无限制</option><option v-for="n in [1,5,10,20]" :value="n">{{n}} MB/s</option></select></label></div></section>
      <section><div class="setting-title"><div class="setting-icon blue"><Download/></div><div><h2>缓存与下载</h2><p>管理磁盘空间和永久音乐</p></div></div><div class="cache-meter"><div><b>音频缓存</b><span>{{(cacheUsed/1024/1024/1024).toFixed(1)}} GB / {{settings.cacheLimitGb}} GB</span></div><div><i :style="{width:Math.min(100,cacheUsed/1024/1024/1024/settings.cacheLimitGb*100)+'%'}"></i></div></div><div class="form-grid"><label>缓存上限<select v-model="settings.cacheLimitGb"><option v-for="n in [2,5,10,20,50]" :value="n">{{n}} GB</option><option :value="9999">无限制</option></select></label><label>下载目录<div class="input-button"><input v-model="settings.downloadDirectory" readonly/><button @click="pickFolder"><FolderSearch/></button></div></label></div><div class="setting-actions"><button class="secondary" @click="clearCache"><Trash2/>清理缓存</button><button class="primary" @click="save"><Check/>保存设置</button></div></section>
     </div>
    </template>
   </section>
  </main>
  <footer class="player"><div class="now"><div class="now-cover"><Music2/></div><div><b>{{current?.title||'尚未播放'}}</b><span>{{current?.artist||'搜索一首喜欢的歌吧'}}</span></div><button v-if="current" @click="favorite(current)"><Heart :fill="current.favorite?'currentColor':'none'"/></button></div><div class="player-center"><div class="controls"><button><Shuffle/></button><button @click="previous"><SkipBack fill="currentColor"/></button><button class="play-main" :disabled="!current" @click="toggle"><Pause v-if="playerState==='playing'" fill="currentColor"/><Play v-else fill="currentColor"/></button><button @click="next"><SkipForward fill="currentColor"/></button><button><Repeat2/></button></div><div class="seek"><span>{{fmt(position)}}</span><div class="range-wrap"><i :style="{width:(buffered/Math.max(1,duration)*100)+'%'}"></i><input type="range" min="0" :max="duration||1" :value="position" @change="seek"/></div><span>{{fmt(duration)}}</span></div></div><div class="player-right"><span v-if="playerState!=='idle'" class="player-label">{{({searching_source:'寻找音源',connecting:'正在连接',queued:'寻找更快来源',downloading:'正在下载',buffering:'正在缓冲',playing:'正在播放',paused:'已暂停',error:'播放失败'} as any)[playerState]||playerState}}</span><button @click="muted=!muted;api.command('set_volume',{volume:muted?0:volume})"><Volume2/></button><input class="volume" type="range" min="0" max="100" v-model="volume" @input="api.command('set_volume',{volume})"/><button @click="showQueue=!showQueue"><ListMusic/></button></div></footer>
  <Transition name="slide"><aside v-if="showQueue" class="drawer"><div class="drawer-head"><div><h2>播放队列</h2><p>{{queue.length}} 首歌曲</p></div><button @click="showQueue=false"><X/></button></div><div class="queue-list"><div v-for="(t,i) in queue" :key="t.id" :class="{playing:t.id===current?.id}"><GripVertical/><span>{{i+1}}</span><div><b>{{t.title}}</b><small>{{t.artist}}</small></div><button @click="play(t)"><Play/></button><button @click="removeQueue(i)"><X/></button></div></div><button v-if="queue.length" class="clear" @click="api.command('clear_queue');queue=[]">清空队列</button></aside></Transition>
  <Transition name="fade"><div v-if="sourceTrack" class="modal-mask" @click.self="sourceTrack=null"><div class="modal"><div class="drawer-head"><div><h2>{{sourceTrack.title}}</h2><p>{{sourceTrack.artist}} · {{sourceTrack.sourceCount}} 个可用来源</p></div><button @click="sourceTrack=null"><X/></button></div><div class="source-head"><span>来源</span><span>质量</span><span>速度</span><span>队列</span><span></span></div><div v-for="(s,i) in sourceTrack.sources||[]" class="source-row"><div><b>{{s.username}}</b><small>{{s.filename}}</small></div><span>{{s.format}} {{s.bitrate?`${s.bitrate}K`:''}}</span><span>{{bytes(s.uploadSpeed||0)}}/s</span><span>{{s.queueLength||0}}</span><button @click="api.command('play_track',{trackId:sourceTrack!.id,sourceId:s.id});sourceTrack=null">使用</button></div><div v-if="!sourceTrack.sources?.length" class="empty-small">来源详情会在在线搜索后显示</div></div></div></Transition>
  <Transition name="fade"><div v-if="onboarding" class="modal-mask onboard"><div class="onboard-card"><div class="onboard-logo"><Music2/></div><template v-if="onboardingStep===0"><span class="eyebrow">欢迎使用</span><h1>让音乐回归简单</h1><p>SoulMusic 会在后台连接 Soulseek，自动寻找合适来源、缓冲并播放。你只需搜索和聆听。</p><div class="legal">Soulseek 中的资源由网络用户提供。请仅访问、播放或下载你拥有合法访问权的内容，并遵守所在地区法律法规。</div><button class="primary big" @click="onboardingStep=1">我知道了，继续 <ChevronRight/></button></template><template v-else><span class="eyebrow">连接网络</span><h1>创建你的音乐身份</h1><p>账号只用于连接 Soulseek 网络，可以自动生成。</p><label class="onboard-input">用户名<input v-model="settings.username" :disabled="settings.autoAccount" placeholder="SoulMusic_8HD29"/></label><label class="onboard-input">密码<input v-model="settings.password" type="password" :disabled="settings.autoAccount"/></label><label class="check"><input type="checkbox" v-model="settings.autoAccount"/> 自动生成临时账号</label><button class="primary big" @click="finishOnboarding">开始使用 <Music2/></button></template></div></div></Transition>
  <Transition name="toast"><div v-if="toast" class="toast">{{toast}}</div></Transition>
 </div>
</template>
